### ISSUE TITLE
Bundle the fonts instead of loading them from Google fonts

### ISSUE THREAD

**Issue by gargakshit** [blenderskool/untab#17]
Bundling the fonts will not make a network request each time untab's frame is injected, increasing performance. As it injects the frame into the page, the font loading (might) block the loading of other content request by the website itself. Also, if we open untab while some page asset is still loading, the asset loading is cancelled and further requests are blocked until untab's fonts are loaded

![image](https://user-images.githubusercontent.com/15605299/94168911-c4a17600-feab-11ea-9940-e1d30ad3d8c5.png)

**Comment by blenderskool** [comment]
Yep, this issue is relevant and can be a good first issue.

Some details for anyone who would want to work on this:
1. Download the Lato font and store it `src/assets/fonts` directory.
2. Load the locally downloaded font instead of loading from Google Fonts.
3. Update the build process to copy `src/assets` directory to `dist/assets` directory.

**Comment by gargakshit** [comment]
Reminds me, please keep this for me :D
I'll do it during the hacktoberfest :)

**Comment by blenderskool** [comment]
Sure @gargakshit :slightly_smiling_face:

**Comment by blenderskool** [comment]
Closed via #23
