### ISSUE TITLE
Untab doesn’t find an open tab

### ISSUE THREAD

**Issue by sinewave** [blenderskool/untab#91]
I often run into the scenario where untab doesn’t always find a tab that I know is open. If I use Chrome's built in tab finder I see it?

Not sure what would be helpful to share here to help debug here as I haven't come across any pattern to the missing tabs? 

Ideas
- Is there a limit on how many tabs untab will remember - perhaps it's that?
- Does untab do any kind of deduping? The most recent tab that caused me to create this issue was the same google slide that was open twice but I can only find one in untab.

Tony

**Comment by blenderskool** [comment]
The tabs query logic might not be fetching all tabs. It does not fetch suspended tabs right now - #62 
The query needs to be updated to fetch all tabs.
In some cases, UnTab might not have permission to fetch certain tabs - eg. tabs in incognito windows cannot be retrieved if UnTab is not "allowed on Incognito windows".

> Does untab do any kind of deduping? The most recent tab that caused me to create this issue was the same google slide that was open twice but I can only find one in untab.

This might be because UnTab does not show the current tab you are on (as why would you switch to the same tab you are on). If this is not the case, then there might be some other issue.

**Comment by blenderskool** [comment]
Closing this as there's no actionable items here. Feel free to open if there's anything.
